---
- name: Server provisioning
  hosts: server*
  tasks:
  - name: Configure Consul server settings
    ansible.builtin.template:
      src: ./consul/server/etc/consul.d/server.hcl.j2
      dest: /etc/consul.d/server.hcl
      owner: root
      group: root

  - name: Enable and start consul.service
    ansible.builtin.service:
      name: consul
      state: restarted
      enabled: true

  # This task makes it so the first server resolves to the domain provided
  - name: Configure hosts file
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ IP_START_SERVERS }}$'
      line: "{{ IP_START_SERVERS }} {{ CONSUL_INTERNAL_DOMAIN }} consul"
      state: present

  - name: Configure Nomad server settings
    ansible.builtin.template:
      src: ./nomad/server/etc/nomad.d/server.hcl.j2
      dest: /etc/nomad.d/server.hcl
      owner: root
      group: root

  - name: Ensure Nomad is restarted
    ansible.builtin.service:
      name: nomad
      state: restarted
      enabled: true

  - name: Ensure HashiCorp Vault is installed
    ansible.builtin.apt:
      pkg:
      - vault
      state: present
    when: VAULT_INSTALL == true

  - name: Ensure Vault server configuration is copied over
    ansible.builtin.template:
      src: ./vault/server/etc/vault.d/vault.hcl.j2
      dest: /etc/vault.d/vault.hcl
      owner: root
      group: root
    when: VAULT_INSTALL == true

  - name: Ensure Vault is enabled and restarted
    ansible.builtin.service:
      name: vault
      state: restarted
      enabled: true

